name: Testes com mocha

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3
      
      - name: Configurar Node.jobs
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      
      - name: Instalar dependências
        run: npm install
      
      - name: Garantir permissões de execução para mocha
        run: chmod +x ./node_modules/.bin/mocha

      - name: Verificar o caminho do mocha
        run: ls -l ./node_modules/.bin/mocha

      - name: Rodar os testes com mocha
        run: npx mocha